# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/win-64/blas-n=3.0-mkl.conda
https://conda.anaconda.org/conda-forge/win-64/ca-certificates-2023.5.7-h56e8100_0.conda
https://repo.anaconda.com/pkgs/main/win-64/icc_rt-2022.n=3.0-h6049295_2.conda
https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-n=3.0-cuda.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2023c-h04d1e81_0.conda
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-14.27.29016-h5e58377_2.conda
https://repo.anaconda.com/pkgs/main/win-64/vc-14.2-h21ff451_1.conda
https://repo.anaconda.com/pkgs/main/win-64/bzip2-n=3.0.8-he774522_0.conda
https://repo.anaconda.com/pkgs/main/win-64/cudatoolkit-11.3.n=3-h59b6b97_2.conda
https://repo.anaconda.com/pkgs/main/win-64/giflib-5.2.n=3-h8cc25b3_3.conda
https://repo.anaconda.com/pkgs/main/win-64/intel-openmp-2023.n=3.0-h59b6b97_46319.conda
https://repo.anaconda.com/pkgs/main/win-64/jpeg-9e-h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/lerc-3.0-hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libdeflate-n=3.17-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libffi-3.4.4-hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libuv-n=3.44.2-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libwebp-base-n=3.2.4-h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/lz4-c-n=3.9.4-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/openssl-3.0.9-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/sqlite-3.41.2-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tbb-2021.8.0-h59b6b97_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tk-8.6.12-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/xz-5.4.2-h8cc25b3_0.conda
https://repo.anaconda.com/pkgs/main/win-64/zlib-n=3.2.13-h8cc25b3_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libpng-n=3.6.39-h8cc25b3_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl-2023.n=3.0-h8bd8f75_46356.conda
https://repo.anaconda.com/pkgs/main/win-64/python-3.10.11-he1021f5_3.conda
https://repo.anaconda.com/pkgs/main/win-64/zstd-n=3.5.5-hd43e919_0.conda
https://conda.anaconda.org/conda-forge/noarch/certifi-2023.5.7-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-2.0.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/freetype-2.12.n=3-ha860e81_0.conda
https://repo.anaconda.com/pkgs/main/win-64/idna-3.4-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/joblib-n=3.2.0-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libtiff-4.5.0-h6c2663c_2.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl-service-2.4.0-py310h2bbff1b_1.conda
https://conda.anaconda.org/conda-forge/noarch/packaging-23.n=3-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pytz-2022.7-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/setuptools-67.8.0-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-n=3.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/threadpoolctl-2.2.0-pyh0d69192_0.conda
https://repo.anaconda.com/pkgs/main/win-64/typing_extensions-4.6.3-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/wheel-0.38.4-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/win_inet_pton-n=3.n=3.0-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/cffi-n=3.15.n=3-py310h2bbff1b_3.conda
https://repo.anaconda.com/pkgs/main/win-64/libwebp-n=3.2.4-hbc33d0d_1.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-n=3.24.3-py310h65a83cf_1.conda
https://repo.anaconda.com/pkgs/main/win-64/pip-23.n=3.2-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pysocks-n=3.7.n=3-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://conda.anaconda.org/pytorch/win-64/pytorch-n=3.12.0-py3.10_cuda11.3_cudnn8_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/brotlipy-0.7.0-py310h2bbff1b_1002.conda
https://repo.anaconda.com/pkgs/main/win-64/cryptography-39.0.n=3-py310h21b164f_2.conda
https://repo.anaconda.com/pkgs/main/win-64/pillow-9.4.0-py310hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pyopenssl-23.0.0-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/urllib3-n=3.26.16-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/requests-2.29.0-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/bottleneck-n=3.3.5-py310h9128911_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_fft-n=3.3.6-py310h4ed8f06_1.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_random-n=3.2.2-py310h4ed8f06_1.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-n=3.24.3-py310h055cbcc_1.conda
https://repo.anaconda.com/pkgs/main/win-64/numexpr-2.8.4-py310h2cd9be0_1.conda
https://repo.anaconda.com/pkgs/main/win-64/scipy-n=3.9.3-py310h309d312_2.conda
https://conda.anaconda.org/pytorch/win-64/torchaudio-0.12.0-py310_cu113.tar.bz2
https://conda.anaconda.org/pytorch/win-64/torchvision-0.13.0-py310_cu113.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pandas-n=3.5.3-py310h4ed8f06_0.conda
https://conda.anaconda.org/anaconda/win-64/scikit-learn-n=3.2.0-py310hd77b12b_1.tar.bz2
